[package]
name = "compio-example"
version = "0.1.0"
edition = "2024"

[dependencies]
compio = { version = "0.17", features = ["macros"] }
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread"] }
